######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 15 22:57:28 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
