######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 15 22:32:23 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += 
SOURCES += helloworld.cpp
